// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfwjucnncbctfxflmjzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmd2p1Y25uY2JjdGZ4ZmxtanprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzE5MTMsImV4cCI6MjA2Mzk0NzkxM30.69qJX6Bk_Oi62IXJdGA134DR3zQyFmkcRLtf-LSOZx8"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);